# Generated by Django 6.0.2 on 2026-02-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Block A Ground Floor, Near Main Gate', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stall_images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['stall__name', 'name']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='preorder.foodstall'),
        ),
    ]
