# Generated by Django 6.0.2 on 2026-02-21 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0002_foodstall_alter_fooditem_options_fooditem_stall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StallOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_code', models.CharField(blank=True, help_text='Auto-generated 5-digit owner ID', max_length=5, unique=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='preorder.foodstall')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stall_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stall__name'],
            },
        ),
    ]
